### ISSUE TITLE
IonSlider::getSlider() was silently deprecated

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-site#1003]
_From @dudeofawesome on February 26, 2017 2:53_

**Ionic version:**
- [x] **2.x**

**I'm submitting a ...**  (check one with "x")
- [x] bug report

**Current behavior:**
`IonSlider::getSlider()` has been deprecated and returns `void`, but this was never mentioned in the release notes.

**Expected behavior:**
Update the release notes to mention this breaking change. I believe this happened in [v2.0.0](https://github.com/driftyco/ionic/releases/tag/v2.0.0).

_Copied from original issue: driftyco/ionic#10560_

**Comment by brandyscarney** [comment]
This was actually here: https://github.com/driftyco/ionic/blob/master/CHANGELOG.md#breaking-changes

Because there were so many changes to the slides we didn't list them all, and just updated the documentation to reflect the new way of using Slides. We could always add a bit about it being deprecated though. 

The advanced section goes over how to use the new properties: http://ionicframework.com/docs/v2/nightly/api/components/slides/Slides/#advanced

**Comment by dudeofawesome** [comment]
Ah, I see. I was unaware of that changelog. It would be nice if the [releases tab](https://github.com/driftyco/ionic/releases) matched that file.

**Comment by brandyscarney** [comment]
@dudeofawesome Updated back to 2.0.0-rc.4 🙂 

https://github.com/driftyco/ionic/releases/tag/v2.0.0-rc.5

**Comment by perrygovier** [comment]
this can be closed now, right?
