### ISSUE TITLE
Guide - iOS mobile testing

### ISSUE THREAD

**Issue by lwenke** [driftyco/ionic-site#149]
http://ionicframework.com/docs/guide/testing.html
It says:
"You can also test the app directly in a mobile browser. For OS X users, Safari on OS X can directly debug websites and simulator applications. First you have to enable the remote web inspector on both the device and Safari on desktop. To do this with iOS 7 and OS X Mavericks, enable the Web Inspector option in the iOS Settings -> Safari -> Advanced section, and also enable the Developer Menu in the Advanced section of the Safari OS X settings."

It also works on my iOS 6 device and it works on installed Ionic apps (not just using the Safari browser in iOS). I didn't know about this feature it is VERY useful.

**Comment by Ionitron** [comment]
Greetings @lwenke!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
