### ISSUE TITLE
Chapter 1: Installation Guide, Updates Needed for Linux and all platforms

### ISSUE THREAD

**Issue by H3Chief** [driftyco/ionic-site#155]
relevant for: http://ionicframework.com/docs/guide/installation.html

##All Platforms Updates

None of the guides mention any dependencies that cordova has for Ant required to add platforms and run builds.  Cordova installation/download has only npm instructions, and doesn't install ant during that installation.  Ant also requires Java jdk (not jre).

This is probably new to many front-end devs looking to break into the mobile space, and makes things tough.  There's actually a TON of criticism on StackOverflow about the documentation :-1: sadly.

Some notes or even a sub chapter on installing these could be helpful.

##Linux updates

The section that asks you to run `ionic platform ios` and `ionic platform android` has a note about windows users not being able to do the ios install.  This implies linux users *can* do this, but community opinion seems to be this isn't possible.

**Note:** If you confirm these things, I have forked and am prepared to add the necessary instructions/updates and submit a pull request.

**Comment by Ionitron** [comment]
Greetings @H3Chief!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
