### ISSUE TITLE
ionicPopup Documentation Error

### ISSUE THREAD

**Issue by dwmay** [driftyco/ionic-site#191]
I am using v1.0.0-beta.1 (not sure if that is the issue) but the documentation for ionicPopup has the 'template' field listed as the place to put the text you want displayed in a confirm, alert, etc. popup window but it should have the 'content' field listed as the place for the window text.

**Comment by Ionitron** [comment]
Greetings @dwmay!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
