### ISSUE TITLE
Building an app with the download (not using the command line tools) and issuing PhoneGap Build (not PhoneGap)

### ISSUE THREAD

**Issue by SubjectiveEffect** [driftyco/ionic-site#198]
It appears this is perfectly legit (from my experiment with the todo app).

a. Am I correct - is it legit?
b. If I'm am correct why isn't it documented?
c. Would you like me to document how you do it?

I develop apps with jQuery Mobile and PhoneGap Build atm but I'm hoping (if this works) to switch to Ionic.

**Comment by Ionitron** [comment]
Greetings @SubjectiveEffect!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
