### ISSUE TITLE
ion-tab hidden attribute is not documented

### ISSUE THREAD

**Issue by calendee** [driftyco/ionic-site#215]
The docs for `ion-tab` don't seem to have the "new" `hidden` attribute : 

http://ionicframework.com/docs/nightly/api/directive/ionTab/

https://github.com/driftyco/ionic/issues/1666

**Comment by Ionitron** [comment]
Greetings @calendee!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
