### ISSUE TITLE
Footer links for Mission and Team broken

### ISSUE THREAD

**Issue by synthable** [driftyco/ionic-site#221]
The links for **Mission** and **Team** in the footer under **Company** lead to nowhere.

**Comment by EMCP** [comment]
This URL is dead too, found in the Protractor E2E testing

http://learn.ionicframework.com/formulas/Protractor/

`https://sourcegraph.com/github.com/exratione/protractor-selenium-server-vagrant/symbols/javascript/commonjs/test/protractor.conf.base.js/-/config`

**Comment by Ionitron** [comment]
Greetings @synthable!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
