### ISSUE TITLE
Mention inputmode attribute in HTML5 input docs?

### ISSUE THREAD

**Issue by cvrebert** [driftyco/ionic-site#229]
Docs page in question is http://ionicframework.com/html5-input-types/#text
For info on `inputmode`, see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-inputmode

**Comment by Ionitron** [comment]
Greetings @cvrebert!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
