### ISSUE TITLE
Cannot scroll terms page

### ISSUE THREAD

**Issue by psalaets** [driftyco/ionic-site#269]
Couldn't find a repo for apps.ionic.io so I'm just reporting this here, sorry.

https://apps.ionic.io/legal

`body` has `overflow: hidden`

**Comment by Ionitron** [comment]
Greetings @psalaets!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
