### ISSUE TITLE
Link $ ionic resources to docs

### ISSUE THREAD

**Issue by matiastucci** [driftyco/ionic-site#275]
In the homepage it says:

> Generate icons and splash screens for all devices and device sizes with a single command. ```$ ionic resources```

In my opinion it would be nice if the ```$ ionic resources``` was link to the [docs](http://ionicframework.com/docs/cli/icon-splashscreen.html)

**Comment by Ionitron** [comment]
Greetings @matiastucci!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
