### ISSUE TITLE
Right arrow missing in List Icons example

### ISSUE THREAD

**Issue by martinjbaker** [driftyco/ionic-site#277]
http://ionicframework.com/docs/components/#item-icons

> The third item has no a right side icon assigned (whichs defaults to the right arrow).

There is no right arrow visible.

**Comment by martinjbaker** [comment]
Just found this
http://forum.ionicframework.com/t/solved-right-arrow-on-list-item-not-automatically-added/4330/6

seems docs are out of date and right arrow is NOT automatically added.

**Comment by Ionitron** [comment]
Greetings @martinjbaker!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
