### ISSUE TITLE
Docs - Guide - Installation: Intermediate directory "ionic-app-base-master"

### ISSUE THREAD

**Issue by bkowshik** [driftyco/ionic-site#280]
Ionic version 1.1.0
http://www.ionicframework.com/docs/guide/installation.html

Running the command.
`$ cd todo && ls`

Does not display the following output as specified.

    ├── bower.json     // bower dependencies
    ├── config.xml     // cordova configuration
    ├── gulpfile.js    // gulp tasks
    ├── hooks          // custom cordova hooks to execute on specific commands
    ├── ionic.project  // ionic configuration
    ├── package.json   // node dependencies
    ├── platforms      // iOS/Android specific builds will reside here
    ├── plugins        // where your cordova/ionic plugins will be installed
    ├── scss           // scss code, which will output to www/css/
    └── www            // application - JS code and libs, CSS, images, etc.

But, the following is displayed.

    ├── ionic-app-base-master
    ├── ionic.project

A directory with name `ionic-app-base-master` is created and inside that are all the files.

**Comment by Ionitron** [comment]
Greetings @bkowshik!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
