### ISSUE TITLE
item-note goes to next line on Firefox

### ISSUE THREAD

**Issue by commaster90** [driftyco/ionic-site#281]
In this demo on the documentation page http://ionicframework.com/docs/components/#item-icons , the item-note is shifted down the next line on Firefox. However, this can be solved by putting the item-note before the text.

```html
<a class="item item-icon-left" href="#">
  <i class="icon ion-mic-a"></i>
  <span class="item-note">
    Grammy
  </span>
  Record album
</a>
```

This same goes with the remaining item-note's. Would anyone fix the documentation?

**Comment by Ionitron** [comment]
Greetings @commaster90!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Comment by roxolan** [comment]
We seem to be affected by this issue on ionic-angular ver. 1.3.2. Is there a chance for you to still have a look into it?
