### ISSUE TITLE
Change doc format to support IDEs

### ISSUE THREAD

**Issue by perrygovier** [driftyco/ionic-site#387]
Dgeni configs will also need to be updated to support this new format

Reference: TypeStrong/atom-typescript#828

**Comment by perrygovier** [comment]
@mhartington can you dig up some examples from more projects that are formatted nicely?

**Comment by mhartington** [comment]
Each editor seems to do it's own thing.
Using NG2 Component as an example

Atom: Autocomplete-plus + Atom Typescript

![screen shot 2016-04-13 at 2 34 03 pm](https://cloud.githubusercontent.com/assets/2835826/14504945/f517db2c-0184-11e6-99d9-19139c4d6131.png)

Just prints the raw output from the typescript compiler. 
https://github.com/atom/autocomplete-plus/issues/662

Brought this up some times around to the plugin maintainers but the didn't want to break anything for anyone else

Code
![screen shot 2016-04-13 at 2 34 54 pm](https://cloud.githubusercontent.com/assets/2835826/14504946/f51c702e-0184-11e6-8633-b0e6f7ea9aaa.png)

Code does this a bit better, as it respects the whitespace in the output, so you get a little bit of a clear description. 


![screen shot 2016-04-13 at 2 38 12 pm](https://cloud.githubusercontent.com/assets/2835826/14505077/96e915d8-0185-11e6-8687-74ad2f3966ae.png)


![screen shot 2016-02-01 at 12 43 29 pm](https://cloud.githubusercontent.com/assets/2835826/12725641/adb63642-c8e1-11e5-94aa-3f524745abcb.png)

### Overall

I don't think our docs awful, but atom is definitely making them not appear great. One suggestion is to build our own companion plugin for atom (do we really want to do that), reformat our docs so that the most of the dgnei stuff is removed at publish time.
