### ISSUE TITLE
docs: Don't scroll sidebar when clicking on an item in the sidebar

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic-site#441]
_From @brandyscarney on January 27, 2016 17:24_

Noticed this in API docs... when you click on anything in the sidebar it scrolls all the way to the top so you can't just click down the list. 

_Copied from original issue: driftyco/ionic#5215_

**Comment by perrygovier** [comment]
This is because they're separate pages so the div scrolling position is reset. This could be fixed with JS, but might be janky. It could also be fixed by making the docs a single page app, but that's a pretty significant undertaking and would have to be done carefully. 

I agree it needs to be fixed, but I'm going to chew on which solution is best for a bit.
