### ISSUE TITLE
Ionic 2 Gesture docs

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-site#792]
_From @rubimazaki on September 26, 2016 11:11_

Please provide us with some basic docs/example of using Ionic2 Gestures?

Current state is most annoying, because you cannot use the old (mousedown) or (mousemove) to create your own mechanism, while gesture handling is provided by Ionic2 just not documented AT ALL. Not even some basic example in the source tree. Nothing... 

Example anyone? 

Thanks :-)

_Copied from original issue: driftyco/ionic#8211_

**Comment by mhartington** [comment]
https://github.com/driftyco/ionic-site/issues/438

**Comment by rubimazaki** [comment]
Really funny how you refer one open bug to another "closed" bug...

There are no docs for gestures, admit it instead of closing the issues. Yeah it looks bad on the statistics, but it is an open bug. And for what I understood, not only there are NO docs about gesture management, the code actually has at least 3~4 different mechanisms overlapping each other: UIEventManager, hammer.js TS wrappers (and Manymore...) with each of the undocumented classes (Gesture, PanGesture, SwipeGesture, ...) using a different API

**Comment by mhartington** [comment]
Please see the comment on the original issue.

https://github.com/driftyco/ionic-site/issues/438#issuecomment-249786058

Some APIs are undocumented and hidden for a reason. They're internal to the framework and are not meant to be used by a developer.
